# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: study.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'study.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstudy.proto\x12\rstudy_service\"G\n\x0cIndexRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x13\n\x0bline_number\x18\x03 \x01(\x05\" \n\rIndexResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"|\n\x0eSearchResponse\x12\x34\n\x07matches\x18\x01 \x03(\x0b\x32#.study_service.SearchResponse.Match\x1a\x34\n\x05Match\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x32\xa5\x01\n\x0bStudyEngine\x12J\n\rIndexDocument\x12\x1b.study_service.IndexRequest\x1a\x1c.study_service.IndexResponse\x12J\n\x0bSearchNotes\x12\x1c.study_service.SearchRequest\x1a\x1d.study_service.SearchResponseB6Z4github.com/Eklund2012/recall/proto/gen/study_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'study_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/Eklund2012/recall/proto/gen/study_service'
  _globals['_INDEXREQUEST']._serialized_start=30
  _globals['_INDEXREQUEST']._serialized_end=101
  _globals['_INDEXRESPONSE']._serialized_start=103
  _globals['_INDEXRESPONSE']._serialized_end=135
  _globals['_SEARCHREQUEST']._serialized_start=137
  _globals['_SEARCHREQUEST']._serialized_end=182
  _globals['_SEARCHRESPONSE']._serialized_start=184
  _globals['_SEARCHRESPONSE']._serialized_end=308
  _globals['_SEARCHRESPONSE_MATCH']._serialized_start=256
  _globals['_SEARCHRESPONSE_MATCH']._serialized_end=308
  _globals['_STUDYENGINE']._serialized_start=311
  _globals['_STUDYENGINE']._serialized_end=476
# @@protoc_insertion_point(module_scope)
