# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import study_pb2 as study__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in study_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StudyEngineStub(object):
    """The "contract" for the Study Engine
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexDocument = channel.unary_unary(
                '/study_service.StudyEngine/IndexDocument',
                request_serializer=study__pb2.IndexRequest.SerializeToString,
                response_deserializer=study__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.SearchNotes = channel.unary_unary(
                '/study_service.StudyEngine/SearchNotes',
                request_serializer=study__pb2.SearchRequest.SerializeToString,
                response_deserializer=study__pb2.SearchResponse.FromString,
                _registered_method=True)


class StudyEngineServicer(object):
    """The "contract" for the Study Engine
    """

    def IndexDocument(self, request, context):
        """Go sends text to Python to be turned into vectors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchNotes(self, request, context):
        """Go asks a question, Python returns the best matches
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudyEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexDocument,
                    request_deserializer=study__pb2.IndexRequest.FromString,
                    response_serializer=study__pb2.IndexResponse.SerializeToString,
            ),
            'SearchNotes': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchNotes,
                    request_deserializer=study__pb2.SearchRequest.FromString,
                    response_serializer=study__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'study_service.StudyEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('study_service.StudyEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StudyEngine(object):
    """The "contract" for the Study Engine
    """

    @staticmethod
    def IndexDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/study_service.StudyEngine/IndexDocument',
            study__pb2.IndexRequest.SerializeToString,
            study__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchNotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/study_service.StudyEngine/SearchNotes',
            study__pb2.SearchRequest.SerializeToString,
            study__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
